// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const DEFAULT_SUPABASE_URL = "https://muryznvaxzszcffrbxpv.supabase.co";
    const DEFAULT_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11cnl6bnZheHpzemNmZnJieHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ0NDExNjksImV4cCI6MjEwMDAxNzE2OX0.RHa_GLUGiRTVBGGCPvOcoLH6rh4IhyNM7YJWeJvI4Uo";

    let SUPABASE_URL = process.env.SUPABASE_URL || DEFAULT_SUPABASE_URL;
    let SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || DEFAULT_SUPABASE_KEY;

    // Se o ambiente Vercel contiver o projeto antigo ou valores vazios, garante o novo banco
    if (!SUPABASE_URL || SUPABASE_URL.includes("xhxlzawgrzmtgilrzout")) {
      SUPABASE_URL = DEFAULT_SUPABASE_URL;
      SUPABASE_PUBLISHABLE_KEY = DEFAULT_SUPABASE_KEY;
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    let claims: any = null;
    let userId: string | null = null;

    // 1. Validação via getClaims
    const { data: claimsData, error: claimsErr } = await supabase.auth.getClaims(token);
    if (!claimsErr && claimsData?.claims?.sub) {
      claims = claimsData.claims;
      userId = claimsData.claims.sub;
    } else {
      // 2. Fallback direto via getUser(token)
      const { data: userData, error: userErr } = await supabase.auth.getUser(token);
      if (!userErr && userData?.user?.id) {
        userId = userData.user.id;
        claims = { sub: userId, email: userData.user.email, ...userData.user.user_metadata };
      } else {
        // 3. Fallback com supabaseAdmin para contornar qualquer assincronia no token cache
        try {
          const { supabaseAdmin } = await import("./client.server");
          const { data: adminData, error: adminErr } = await supabaseAdmin.auth.getUser(token);
          if (!adminErr && adminData?.user?.id) {
            userId = adminData.user.id;
            claims = { sub: userId, email: adminData.user.email, ...adminData.user.user_metadata };
          }
        } catch {
          // ignora erro do import
        }
      }
    }

    if (!userId || !claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    return next({
      context: {
        supabase,
        userId,
        claims,
      },
    });
  },
);
